{
  "hash": "1d63a5a4247a9efcff5714cb57eb784b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Christine\"\ndate: October 10, 2025\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\ncensus_api_key(\"20068788c6e79d5716fbceb0dcd562ab23f74ca1\")\n\n# Load spatial data\n# 1. Pennsylvania county boundaries\npa_counties <- st_read(here(\"labs/lab_2/data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\MUSA5080PPA\\portfolio-setup-ChristineCui12\\labs\\lab_2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Pennsylvania hospitals (from lecture data)\nhospitals <- st_read(here(\"labs/lab_2/data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\MUSA5080PPA\\portfolio-setup-ChristineCui12\\labs\\lab_2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Pennsylvania census tracts\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#check the CRS\ncat(\"1. PA Counties:\", st_crs(pa_counties)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1. PA Counties: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"2. Hospitals:\", st_crs(hospitals)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2. Hospitals: WGS 84 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"3. Census Tracts:\", st_crs(census_tracts)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3. Census Tracts: NAD83 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- How many hospitals are in your dataset?  \n  - 223\n\n- How many census tracts?  \n  - 3,445\n\n- What coordinate reference system is each dataset in?  \n  - PA county boundaries CRS: PCS WGS 84 / Pseudo-Mercator  \n  - PA hospitals CRS: GCS WGS 84  \n  - PA census tracts CRS: GCS NAD 83\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nacs_vars <- c(\n  total_pop = \"B01003_001\",\n  med_hh_income = \"B19013_001\",\n  # Male 65 years and over (sum of 6 categories)\n  male_65_66 = \"B01001_020\",\n  male_67_69 = \"B01001_021\",\n  male_70_74 = \"B01001_022\",\n  male_75_79 = \"B01001_023\",\n  male_80_84 = \"B01001_024\",\n  male_85_up = \"B01001_025\",\n  # Female 65 years and over (sum of 6 categories)\n  female_65_66 = \"B01001_044\",\n  female_67_69 = \"B01001_045\",\n  female_70_74 = \"B01001_046\",\n  female_75_79 = \"B01001_047\",\n  female_80_84 = \"B01001_048\",\n  female_85_up = \"B01001_049\"\n)\n\npa_demographics <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = acs_vars,\n  output = \"wide\",\n  year = 2022, \n  geometry = FALSE \n) %>%\n  # Calculate the combined 65+ population and rename variables\n  mutate(\n    pop_65_over = male_65_66E + male_67_69E + male_70_74E + male_75_79E + male_80_84E + male_85_upE +\n                  female_65_66E + female_67_69E + female_70_74E + female_75_79E + female_80_84E + female_85_upE\n  ) %>%\n  # Select and rename final columns for clarity and consistency\n  select(\n    GEOID,\n    total_pop = total_popE,\n    med_hh_income = med_hh_incomeE,\n    pop_65_over\n  )\n# Join to tract boundaries\npa_tracts_demographics <- census_tracts %>%\n left_join(pa_demographics, by = \"GEOID\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#tracts have missing income data\nmissing_income_count <- pa_tracts_demographics %>%\n  summarise(missing_count = sum(is.na(med_hh_income))) %>%\n  pull(missing_count)\n#median income across all PA census tracts\nmedian_tract_income <- pa_tracts_demographics %>%\n  filter(!is.na(med_hh_income)) %>%\n  summarise(median_income = median(med_hh_income)) %>%\n  pull(median_income)\n```\n:::\n\n\n**Questions to answer:**\n\n- What year of ACS data are you using?  \n  - 2022 ACS data\n\n- How many tracts have missing income data?  \n  - 62 tracts\n\n- What is the median income across all PA census tracts?  \n  - $70,188\n  \n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:  \n1. Low median household income (choose an appropriate threshold)  \n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\npa_tracts_demographics <- pa_tracts_demographics %>%\n  mutate(pct_65_over = (pop_65_over / total_pop) * 100)\n\nincome_threshold <- quantile(pa_tracts_demographics$med_hh_income, 0.25, na.rm = TRUE)\nelderly_threshold <- quantile(pa_tracts_demographics$pct_65_over, 0.75, na.rm = TRUE)\n\npa_tracts_demographics <- pa_tracts_demographics %>%\n  mutate(\n    income_low = med_hh_income < income_threshold,\n    elderly_high = pct_65_over > elderly_threshold,\n    vulnerable = if_else(income_low & elderly_high, TRUE, FALSE)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary: how many tracts are vulnerable?\nvulnerable_summary <- pa_tracts_demographics %>%\n  summarise(\n    total_tracts = n(),\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    pct_vulnerable = round((vulnerable_tracts / total_tracts) * 100, 1)\n  )\n\nvulnerable_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  NAD83\n  total_tracts vulnerable_tracts pct_vulnerable                       geometry\n1         3445               165            4.8 POLYGON ((-75.13022 39.9585...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- What income threshold did you choose and why?  \n  - I defined low-income tracts as those with a median household income below the 25th percentile of all Pennsylvania census tracts. This data-driven threshold identifies the bottom quarter of tracts in terms of income, representing communities that are relatively economically disadvantaged compared to the rest of the state. Using a percentile-based cutoff avoids arbitrary dollar amounts and allows for consistent comparison across regions and time periods.  \n  \n- What elderly population threshold did you choose and why?  \n  - I defined tracts with a significant elderly population as those where the percentage of residents aged 65 and over exceeds the 75th percentile statewide. This threshold highlights the top quartile of tracts with the highest concentration of older adults—populations that are more likely to experience increased healthcare needs and mobility challenges. By focusing on the upper quartile, the analysis targets areas where aging demographics are most pronounced and where healthcare accessibility is especially critical.  \n  \n- How many tracts meet your vulnerability criteria?  \n  - 165 tracts  \n  \n- What percentage of PA census tracts are considered vulnerable by your definition?  \n  - 4.8%\n  \n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\npa_tracts_proj <- st_transform(pa_tracts_demographics, crs = 4326)\nhospitals_proj <- st_transform(hospitals, crs = 4326)\n\n# Calculate distance from each tract centroid to nearest hospital 中心点 (Centroid)\ntract_centroids <- st_centroid(pa_tracts_proj)\n\nnearest_dist_m <- st_distance(tract_centroids, hospitals_proj) %>%\n  apply(1, min)  # minimum distance for each tract\npa_tracts_proj <- pa_tracts_proj %>%\n  mutate(\n    dist_to_hospital_m = nearest_dist_m,\n    dist_to_hospital_mi = dist_to_hospital_m / 1609.34\n  )\n\nvulnerable_distance_summary <- pa_tracts_proj %>%\n  filter(vulnerable == TRUE) %>%\n  summarise(\n    avg_distance_mi = mean(dist_to_hospital_mi, na.rm = TRUE),\n    max_distance_mi = max(dist_to_hospital_mi, na.rm = TRUE),\n    over_15_miles = sum(dist_to_hospital_mi > 15, na.rm = TRUE)\n  )\n\nvulnerable_distance_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -80.51942 ymin: 39.72143 xmax: -75.00539 ymax: 42.13183\nGeodetic CRS:  WGS 84\n  avg_distance_mi max_distance_mi over_15_miles                       geometry\n1        4.742913        19.18347            10 MULTIPOLYGON (((-75.2495 39...\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n\n- What is the average distance to the nearest hospital for vulnerable tracts?  \n  - 4.75 miles\n\n- What is the maximum distance?  \n  - 19.32 miles\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?  \n  - 10 tracts\n\n- Why you chose your projection  \n  - For this analysis, I used the NAD83 / Conus Albers Equal Area projection (EPSG:5070). This projection is commonly used for spatial analysis across the continental United States because it preserves both area and distance reasonably well over large regions. Pennsylvania spans multiple UTM zones, so using a single statewide or national projection like Albers Equal Area helps avoid spatial distortion that would occur near zone boundaries. The units of this projection are in meters, which allows for accurate distance calculations when measuring the proximity of census tracts to hospitals. Overall, EPSG:5070 provides a balance between accuracy and consistency, making it appropriate for statewide healthcare accessibility analysis.\n  \n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\npa_tracts_proj <- pa_tracts_proj %>%\n  mutate(\n    underserved = if_else(vulnerable == TRUE & dist_to_hospital_mi > 15, TRUE, FALSE)\n  )\n# Summarize underserved tracts\nunderserved_summary <- pa_tracts_proj %>%\n  summarise(\n    total_tracts = n(),\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = round((underserved_tracts / vulnerable_tracts) * 100, 1)\n  )\n\nunderserved_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 4 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  WGS 84\n  total_tracts vulnerable_tracts underserved_tracts pct_underserved\n1         3445               165                 10             6.1\n                        geometry\n1 POLYGON ((-75.13022 39.9585...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- How many tracts are underserved?  \n  - 10 tracts\n- What percentage of vulnerable tracts are underserved?  \n  - 6.1%\n- Does this surprise you? Why or why not?  \n  - The results show that only a small percentage of vulnerable tracts are located more than 15 miles from the nearest hospital. This is not particularly surprising, as Pennsylvania has a relatively dense healthcare network, especially around urban and suburban areas. However, the underserved tracts that do exist are likely concentrated in rural or mountainous regions where population density is low and travel distances are longer. These areas may require targeted healthcare investment or mobile medical services to improve access.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties_proj <- st_transform(pa_counties, st_crs(pa_tracts_proj))\ntracts_county_join <- st_join(pa_tracts_proj, pa_counties_proj, join = st_intersects, left = TRUE)\n\n# Aggregate statistics by county\ncounty_summary <- tracts_county_join %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    n_tracts = n(),\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved_vulnerable = round((underserved_tracts / vulnerable_tracts) * 100, 1),\n    avg_distance_vulnerable = mean(dist_to_hospital_mi[vulnerable == TRUE], na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop[vulnerable == TRUE], na.rm = TRUE),\n    underserved_vulnerable_pop = sum(total_pop[vulnerable == TRUE & underserved == TRUE], na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved_vulnerable))\n\nhead(county_summary, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 8\n   COUNTY_NAM n_tracts vulnerable_tracts underserved_tracts\n   <chr>         <int>             <int>              <int>\n 1 BRADFORD         23                 1                  1\n 2 COLUMBIA         30                 1                  1\n 3 JUNIATA          20                 1                  1\n 4 MONROE           72                 1                  1\n 5 PERRY            29                 2                  2\n 6 SULLIVAN         13                 1                  1\n 7 CLINTON          21                 2                  1\n 8 DAUPHIN          83                 2                  1\n 9 FOREST           12                 2                  1\n10 HUNTINGDON       29                 2                  1\n# ℹ 4 more variables: pct_underserved_vulnerable <dbl>,\n#   avg_distance_vulnerable <dbl>, total_vulnerable_pop <dbl>,\n#   underserved_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot map of percent underserved by Pennsylvania counties.\n\ncounty_map <- pa_counties_proj %>%\n  left_join(county_summary %>% select(COUNTY_NAM, pct_underserved_vulnerable),\n            by = c(\"COUNTY_NAM\" = \"COUNTY_NAM\"))\n\nggplot() +\n  # Counties filled by % underserved vulnerable tracts\n  geom_sf(data = county_map, aes(fill = pct_underserved_vulnerable), \n          color = \"white\", size = 0.3) +\n  \n  # Color scale for underserved percentage\n  scale_fill_viridis_c(\n    name = \"Percent Underserved\",\n    option = \"viridis\",  \n    direction = -1,\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  \n  # Map titles and caption\n  labs(\n    title = \"PERCENT UNDERSERVED BY PENNSYLVANIA COUNTIES\",\n    subtitle = \"Pennsylvania, US\",\n    caption = \"Data sources: ACS (2022)\"\n  ) +\n  \n  # Clean minimal theme with custom styling\n  theme_void() +\n  theme(\n    panel.background = element_rect(fill = \"white\", color = NA),\n    plot.background = element_rect(fill = \"white\", color = NA),\n    plot.title = element_text(\n      size = 14, \n      face = \"bold\", \n      hjust = 0.5,\n      margin = margin(b = 5, unit = \"pt\")\n    ),\n    plot.subtitle = element_text(\n      size = 10, \n      hjust = 0.5,\n      margin = margin(b = 15, t = 5, unit = \"pt\")\n    ),\n    legend.title = element_text(\n      size = 11, \n      face = \"bold\"\n    ),\n    legend.text = element_text(\n      size = 10,\n    ),\n    plot.caption = element_text(\n      size = 9, \n      color = \"gray40\",\n      face = \"italic\",\n      margin = margin(t = 10, unit = \"pt\")\n    ),\n    legend.position = \"right\",\n    legend.box.margin = margin(l = 0, unit = \"pt\")\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts  \n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved  \n- Average distance to nearest hospital for vulnerable tracts  \n- Total vulnerable population  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop5_pct <- county_summary %>% \n  arrange(desc(pct_underserved_vulnerable)) %>% \n  slice_head(n = 5)\ntop5_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  COUNTY_NAM n_tracts vulnerable_tracts underserved_tracts\n  <chr>         <int>             <int>              <int>\n1 BRADFORD         23                 1                  1\n2 COLUMBIA         30                 1                  1\n3 JUNIATA          20                 1                  1\n4 MONROE           72                 1                  1\n5 PERRY            29                 2                  2\n# ℹ 4 more variables: pct_underserved_vulnerable <dbl>,\n#   avg_distance_vulnerable <dbl>, total_vulnerable_pop <dbl>,\n#   underserved_vulnerable_pop <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\ntop1_pop <- county_summary %>% \n  arrange(desc(underserved_vulnerable_pop)) %>% \n  slice_head(n = 1)\ntop1_pop\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  COUNTY_NAM n_tracts vulnerable_tracts underserved_tracts\n  <chr>         <int>             <int>              <int>\n1 PERRY            29                 2                  2\n# ℹ 4 more variables: pct_underserved_vulnerable <dbl>,\n#   avg_distance_vulnerable <dbl>, total_vulnerable_pop <dbl>,\n#   underserved_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?  \n  - The top five counties with the highest percentage of underserved vulnerable tracts are BRADFORD,COLUMBIA,JUNIATA,MONROE and PERRY. They are primarily rural, located in northern and central Pennsylvania. These areas tend to have sparse hospital coverage and lower population density, contributing to longer travel distances for healthcare access.\n  \n- Which counties have the most vulnerable people living far from hospitals?  \n  - PERRY has the largest underserved vulnerable population, reflecting both a relatively high overall share of vulnerable residents and the presence of several tracts located far from hospitals. This suggests that limited healthcare infrastructure and rural settlement patterns contribute to significant access challenges for vulnerable groups in the county.\n  \n- Are there any patterns in where underserved counties are located?  \n  - Underserved counties are primarily located in rural and mountainous regions of Pennsylvania, particularly in the north-central and western parts of the state. These areas have lower population density, fewer major healthcare facilities, and longer travel distances between communities, making them more susceptible to healthcare access inequities.\n  \n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(scales)\n\n# 7.1 Select and format key variables for display\npriority_counties <- county_summary %>%\n  arrange(desc(pct_underserved_vulnerable)) %>%    \n  slice_head(n = 10) %>%    \n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = vulnerable_tracts,\n    `Underserved Tracts` = underserved_tracts,\n    `% Underserved` = pct_underserved_vulnerable,\n    `Avg Distance (mi)` = avg_distance_vulnerable,\n    `Total Vulnerable Population` = total_vulnerable_pop\n  ) %>%\n  mutate(\n    `Total Vulnerable Population` = comma(`Total Vulnerable Population`),  # add commas\n    `% Underserved` = percent(`% Underserved` / 100, accuracy = 0.1),\n    `Avg Distance (mi)` = round(`Avg Distance (mi)`, 1)\n  )\n\n# 2. Create professional summary table\nkable(\n  priority_counties,\n  caption = \"Table 1. Top 10 Pennsylvania Counties with the Highest Percentage of Underserved Vulnerable Tracts\",\n  align = \"lccccc\",\n  digits = 1,\n  format = \"html\"\n)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n<caption>Table 1. Top 10 Pennsylvania Counties with the Highest Percentage of Underserved Vulnerable Tracts</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> County </th>\n   <th style=\"text-align:center;\"> Vulnerable Tracts </th>\n   <th style=\"text-align:center;\"> Underserved Tracts </th>\n   <th style=\"text-align:center;\"> % Underserved </th>\n   <th style=\"text-align:center;\"> Avg Distance (mi) </th>\n   <th style=\"text-align:center;\"> Total Vulnerable Population </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> BRADFORD </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 16.7 </td>\n   <td style=\"text-align:center;\"> 5,466 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> COLUMBIA </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 16.9 </td>\n   <td style=\"text-align:center;\"> 918 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> JUNIATA </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 15.9 </td>\n   <td style=\"text-align:center;\"> 1,782 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONROE </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 17.7 </td>\n   <td style=\"text-align:center;\"> 1,299 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PERRY </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 17.6 </td>\n   <td style=\"text-align:center;\"> 5,800 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SULLIVAN </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100.0% </td>\n   <td style=\"text-align:center;\"> 16.9 </td>\n   <td style=\"text-align:center;\"> 918 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLINTON </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50.0% </td>\n   <td style=\"text-align:center;\"> 11.0 </td>\n   <td style=\"text-align:center;\"> 5,124 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DAUPHIN </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50.0% </td>\n   <td style=\"text-align:center;\"> 10.0 </td>\n   <td style=\"text-align:center;\"> 8,410 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FOREST </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50.0% </td>\n   <td style=\"text-align:center;\"> 15.2 </td>\n   <td style=\"text-align:center;\"> 4,406 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HUNTINGDON </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50.0% </td>\n   <td style=\"text-align:center;\"> 15.0 </td>\n   <td style=\"text-align:center;\"> 4,340 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nlibrary(ggplot2)\nlibrary(viridis)\n\ncounty_map_data <- pa_counties_proj %>%\n  left_join(county_summary, by = c(\"COUNTY_NAM\" = \"COUNTY_NAM\"))\n\nggplot() +\n  # Counties filled by % underserved vulnerable tracts\n  geom_sf(data = county_map_data, aes(fill = pct_underserved_vulnerable), \n          color = \"white\", size = 0.3) +\n  \n  # Hospital locations as points\n  geom_sf(data = hospitals_proj, aes(color = \"Hospitals\"), \n          size = 1, alpha = 0.7, show.legend = \"point\") +\n  \n  # Color scale for access challenge\n  scale_fill_viridis(\n    name = \"Percent Underserved\",\n    option = \"C\",\n    direction = -1,\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  \n  # Hospital point color scale\n  scale_color_manual(\n    name = \"\",\n    values = c(\"Hospitals\" = \"red2\")\n  ) +\n  \n  # Map titles and caption\n  labs(\n    title = \"URDERSERVED COUNTIES AND HOSPITAL LOCATION\",\n    subtitle = \"Pennsylvania, US\",\n    caption = \"Data sources: ACS (2022), Pennsylvania Hospital Data\"\n  ) +\n  \n  # Clean minimal theme with custom styling\n  theme_void() +\n  theme(\n    panel.background = element_rect(fill = \"white\", color = NA),\n    plot.background = element_rect(fill = \"white\", color = NA),\n    plot.title = element_text(\n      size = 14, \n      face = \"bold\", \n      hjust = 0.5,\n      margin = margin(b = 5, unit = \"pt\")\n    ),\n    plot.subtitle = element_text(\n      size = 10, \n      hjust = 0.5,\n      margin = margin(b = 15, t = 5, unit = \"pt\")\n    ),\n    legend.title = element_text(\n      size = 11, \n      face = \"bold\"\n    ),\n    legend.text = element_text(\n      size = 10,\n    ),\n    plot.caption = element_text(\n      size = 9, \n      color = \"gray40\",\n      face = \"italic\",\n      margin = margin(t = 10, unit = \"pt\")\n    ),\n    legend.position = \"right\",\n    legend.box.margin = margin(l = 10, unit = \"pt\")\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nggplot() +\n  # 1. 所有普查区背景（灰色）——表示非弱势区域\n  geom_sf(data = pa_tracts_proj, fill = \"grey90\", color = NA) +\n  \n  # 2. 弱势但不服务不足的区域（浅黄色）\n  geom_sf(data = filter(pa_tracts_proj, vulnerable == TRUE & underserved == FALSE),\n          fill = \"#FED976\", color = NA) +\n  \n  # 3. 服务不足的弱势区域（亮红色，最突出）\n  geom_sf(data = filter(pa_tracts_proj, underserved == TRUE & vulnerable == TRUE),\n          fill = \"#E31A1C\", color = \"white\", size = 0.05) +\n  \n  # 4. 县界线（白色）\n  geom_sf(data = pa_counties_proj, fill = NA, color = \"white\", size = 0.3) +\n  \n  # 5. 医院位置（蓝色点）\n  geom_sf(data = hospitals_proj, color = \"blue\", size = 0.8, alpha = 0.7) +\n  \n  # 6. 添加标题、说明与数据来源\n  labs(\n    title = \"Underserved Vulnerable Tracts in Pennsylvania\",\n    subtitle = \"Red areas represent vulnerable tracts located more than 15 miles from the nearest hospital\",\n    caption = \"Data sources: ACS (2022)\"\n  ) +\n  \n  # 7. 设置样式\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 18, face = \"bold\"),\n    plot.subtitle = element_text(size = 12),\n    plot.caption = element_text(size = 9, color = \"grey50\",face = \"italic\",)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nlibrary(ggplot2)\nlibrary(scales)\n\nvulnerable_tract <- pa_tracts_demographics %>%\n  filter(vulnerable == TRUE)\nggplot(\n  # 1. 筛选出脆弱区域的数据进行绘图\n  data = pa_tracts_proj %>% filter(vulnerable == TRUE), \n  aes(x = dist_to_hospital_mi)\n) +\n  # 2. 使用 geom_histogram 并设置 weight = total_pop\n  #    这使得直方图的条高代表该距离范围内的总人口数\n  geom_histogram(\n    aes(y = after_stat(count), weight = total_pop), \n    bins = 30, \n    fill = \"#74add1\", \n    color = \"white\", \n    alpha = 0.8\n  ) +\n  # 3. 删除 geom_density()：密度图不适用于加权人口总数直方图\n  \n  # 4. 垂直线和标注\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\", size = 1) +\n  # 注意：y 轴现在是人口数，0.02 可能太小，需要调整 y 轴标注位置\n  # 假设最大人口数大约在 100,000 左右，将 y 调整为 10000 \n  annotate(\"text\", x = 15.5, y = 10000, label = \"15-mile threshold\", hjust = 0, color = \"red\", size = 3) +\n  \n  # 5. 标签和主题\n  labs(\n    title = \"Distribution of Hospital Distance for Vulnerable Population\",\n    subtitle = \"Histogram weighted by the total population of vulnerable census tracts\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    # Y 轴标签现在代表人口数量\n    y = \"Total Vulnerable Population Count\", \n    caption = \"Source: ACS (2022), Pennsylvania Hospital Data\"\n  ) +\n  scale_y_continuous(labels = scales::comma) + # 格式化 Y 轴数字\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 11),\n    plot.caption = element_text(size = 9, color = \"gray50\")\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n**Interpretation:** The distribution reveals that the vast majority of vulnerable populations reside within 5 miles of healthcare facilities, with a sharp decline in population counts as distance increases. However, a small but significant number of vulnerable individuals still face substantial barriers, living more than 15 miles from the nearest hospital, highlighting persistent healthcare access disparities in remote areas of Pennsylvania.\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nparks <- st_read(here(\"labs/lab_2/data/PPR_Properties.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Properties' from data source \n  `D:\\MUSA5080PPA\\portfolio-setup-ChristineCui12\\labs\\lab_2\\data\\PPR_Properties.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 504 features and 25 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28353 ymin: 39.87117 xmax: -74.95865 ymax: 40.13186\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ntrees <- st_read(here(\"labs/lab_2/data/ppr_tree_canopy_points_2015.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ppr_tree_canopy_points_2015' from data source \n  `D:\\MUSA5080PPA\\portfolio-setup-ChristineCui12\\labs\\lab_2\\data\\ppr_tree_canopy_points_2015.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 2480 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.26242 ymin: 39.88838 xmax: -74.95928 ymax: 40.13635\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Transform to match our previous analysis (EPSG:4326)\nparks_proj <- st_transform(parks, crs = 4326)\ntrees_proj <- st_transform(trees, crs = 4326)\n\n# Basic summary statistics\ncat(\"\\n--- Summary Statistics ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Summary Statistics ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total parks in Philadelphia:\", nrow(parks), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal parks in Philadelphia: 504 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total street trees in Philadelphia:\", nrow(trees), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal street trees in Philadelphia: 2480 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Get Philadelphia-specific census tracts and demographics for the analysis\n# 下载费城县的 tract-level 数据 (geometry = TRUE 会包含地理边界)\nphilly_tracts <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",        # 总人口\n    median_income = \"B19013_001\",    # 家庭收入中位数\n    white = \"B02001_002\",            # 白人\n    black = \"B02001_003\",            # 黑人\n    asian = \"B02001_005\",            # 亚裔\n    hispanic = \"B03003_003\"          # 西语裔\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE,\n  year = 2022,\n  survey = \"acs5\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |===================================================                   |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_tracts <- philly_tracts %>%\n  select(GEOID, NAME, variable, estimate, geometry) %>%\n  st_as_sf() %>%\n  st_transform(3857) %>%  # 投影到适合空间计算的坐标（如 Web Mercator）\n  pivot_wider(names_from = variable, values_from = estimate) %>%\n  mutate(\n    pct_white = white / total_pop * 100,\n    pct_black = black / total_pop * 100,\n    pct_asian = asian / total_pop * 100,\n    pct_hispanic = hispanic / total_pop * 100,\n    pct_nonwhite = 100 - pct_white\n  )\n\nphilly_tracts_proj <- st_transform(philly_tracts, crs = 4326)\n\ncat(\"\\n--- Summary Statistics ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Summary Statistics ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total tracts in Philadelphia:\", nrow(philly_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal tracts in Philadelphia: 408 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- What dataset did you choose and why?  \n  - I chose three datasets for this analysis: PPR Properties (parks), PPR Tree Canopy Points (street trees), and demographic data from the U.S. Census Bureau's American Community Survey (ACS) for Philadelphia census tracts. These datasets were selected to address the Green Space Equity challenge, which aims to answer the question: \"Do low-income and minority neighborhoods have equitable access to green space?\" To investigate this, I need spatial data on green infrastructure (parks and trees) and demographic data (like race and income) at a neighborhood level (census tracts).\n- What is the data source and date?  \n  - Parks & Trees: The data comes from Philadelphia Parks & Recreation (PPR), likely sourced from OpenDataPhilly. The tree canopy data is explicitly from 2015, as indicated by the filename (ppr_tree_canopy_points_2015.geojson). The date for the park properties is not specified in the file name but is assumed to be a contemporary dataset from the same source.  \n  - Census Demographics: The data is from the U.S. Census Bureau. Specifically, it's the 2022 American Community Survey (ACS) 5-Year Estimates.\n- How many features does it contain?  \n  - The parks data has 504 features, trees data has 2480 features, and census data has 408 features.\n- What CRS is it in? Did you need to transform it?  \n  - The original CRS for the parks and trees datasets is not stated in the code, but it is clear that a transformation was necessary. Both the parks and trees datasets were immediately re-projected to WGS 84 (EPSG: 4326) to ensure they align. Similarly, the census tract data, after being downloaded, was transformed first to a projected CRS suitable for spatial calculations (EPSG: 3857) and then to WGS 84 (EPSG: 4326) to match the other layers. This standardization is crucial for performing accurate spatial operations.\n\n---\n\n2. **Pose a research question**\n\n- **Do low-income and minority neighborhoods have equitable access to green space?**\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n# --- 1. Calculate park and tree accessibility metrics ---\n\n# Compute centroids for each census tract\ntract_centroids <- st_centroid(philly_tracts_proj)\n\n# Calculate distance (in meters) from each tract centroid to the nearest park\ndist_to_park <- st_distance(tract_centroids, parks_proj) %>%\n  apply(1, min)  # min distance for each tract\n\n# Calculate distance to the nearest tree canopy point (proxy for green coverage)\ndist_to_tree <- st_distance(tract_centroids, trees_proj) %>%\n  apply(1, min)\n\n# Add distance variables back to tracts\nphilly_tracts_proj <- philly_tracts_proj %>%\n  mutate(\n    dist_to_park_m = as.numeric(dist_to_park),\n    dist_to_tree_m = as.numeric(dist_to_tree),\n    dist_to_park_km = dist_to_park_m / 1000,\n    dist_to_tree_km = dist_to_tree_m / 1000\n  )\n\n# --- 2. Explore correlations between green access and demographics ---\n\n# Examine whether lower-income or higher-nonwhite areas are farther from green space\ncor_test_income <- cor.test(philly_tracts_proj$median_income, philly_tracts_proj$dist_to_park_km, use = \"complete.obs\")\ncor_test_nonwhite <- cor.test(philly_tracts_proj$pct_nonwhite, philly_tracts_proj$dist_to_park_km, use = \"complete.obs\")\n\ncat(\"\\n--- Correlation Results ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Correlation Results ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Income vs. Distance to Park (r):\", round(cor_test_income$estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIncome vs. Distance to Park (r): -0.132 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Pct Nonwhite vs. Distance to Park (r):\", round(cor_test_nonwhite$estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPct Nonwhite vs. Distance to Park (r): 0.104 \n```\n\n\n:::\n\n```{.r .cell-code}\n# --- 3. Classify tracts by socioeconomic characteristics ---\n\nincome_median <- median(philly_tracts_proj$median_income, na.rm = TRUE)\nnonwhite_median <- median(philly_tracts_proj$pct_nonwhite, na.rm = TRUE)\n\nphilly_tracts_proj <- philly_tracts_proj %>%\n  mutate(\n    income_group = if_else(median_income < income_median, \"Low Income\", \"High Income\"),\n    race_group = if_else(pct_nonwhite > nonwhite_median, \"High Nonwhite\", \"Low Nonwhite\")\n  )\n\n# --- 4. Visualize distance to parks by income and race group ---\n\n# Boxplot comparison\nggplot(philly_tracts_proj %>% st_drop_geometry(), \n       aes(x = income_group, y = dist_to_park_km, fill = race_group)) +\n  geom_boxplot(alpha = 0.8, outlier.color = \"gray40\") +\n  scale_fill_viridis_d(name = \"Race Group\") +\n  labs(\n    title = \"Park Accessibility by Income and Racial Composition\",\n    subtitle = \"Philadelphia Census Tracts (2022 ACS + OpenDataPhilly)\",\n    x = \"Income Group\",\n    y = \"Distance to Nearest Park (km)\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# --- 5. Map visualization: spatial distribution of green access ---\ngreen_access_map <- ggplot(philly_tracts_proj) +\n  # 普查区按到公园距离填充颜色\n  geom_sf(\n    aes(fill = dist_to_park_km),\n    color = \"white\",\n    linewidth = 0.1\n  ) +\n  # 公园边界\n  geom_sf(\n    data = parks_proj, \n    fill = \"#74c476\", \n    color = \"#006d2c\", \n    alpha = 0.7,\n    linewidth = 0.3\n  ) +\n  # 树木位置（抽样显示以避免过度拥挤）\n  geom_sf(\n    data = trees_proj %>% sample_n(min(5000, nrow(trees_proj))),  # 限制显示数量\n    color = \"#238b45\",\n    size = 0.1,\n    alpha = 0.3\n  ) +\n  # 使用绿色系连续色标\n  scale_fill_gradientn(\n    name = \"Distance to Park (km)\",\n    colors = c(\"#f7fcf5\", \"#e5f5e0\", \"#c7e9c0\", \"#a1d99b\", \"#74c476\", \"#41ab5d\", \"#238b45\", \"#006d2c\", \"#00441b\"),\n    limits = c(0, max(philly_tracts_proj$dist_to_park_km, na.rm = TRUE)),\n    na.value = \"grey80\"\n  ) +\n  labs(\n    title = \"GREEN SPACE ACCESSIBILITY IN PHILADELPHIA\",\n    subtitle = \"Distance to Nearest Park by Census Tract\",\n    caption = \"Data sources: ACS (2022)\"\n  ) +\n  theme_void()\n\n# 应用主题样式\ngreen_access_map + theme(\n  panel.background = element_rect(fill = \"white\", color = NA),\n  plot.background = element_rect(fill = \"white\", color = NA),\n  legend.box.margin = margin(l = 10, unit = \"pt\"),\n  legend.title = element_text(face = \"bold\", size = 10),\n  legend.text = element_text(size = 8),\n  plot.title = element_text(face = \"bold\", size = 16, hjust = 0.5),\n  plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(b = 15, t = 5, unit = \"pt\")),\n  plot.caption = element_text(margin = margin(t = 15, unit = \"pt\"), face = \"italic\", size = 9)\n)\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nThe spatial analysis and the provided visualizations suggest a clear pattern of inequitable access to parks in Philadelphia based on both race and income.  \nThe statistical analysis showed a positive correlation between the percentage of nonwhite residents and distance to the park (r≈0.288), and a negative correlation between median income and park distance (r≈−0.197). This means that census tracts with a higher proportion of nonwhite residents or lower incomes tend to be farther away from the nearest park.  \nThe boxplot clearly visualizes this disparity:  \n  - High Nonwhite tracts consistently exhibit a higher median distance to the nearest park compared to Low Nonwhite tracts, regardless of the income group.  \n  - The most spatially disadvantaged group is the Low Income / High Nonwhite group, which has a median park distance of about 0.35 km, significantly higher than the High Income / Low Nonwhite group's median of approximately 0.2 km.  \nThe choropleth map, \"Green Space Accessibility in Philadelphia,\" visually confirms this pattern, showing that the darkest green areas (closest proximity to parks) are concentrated along the major river parks, while lighter green and white areas (lower accessibility) are prevalent in parts of North and Northeast Philadelphia, regions that often correlate with the socioeconomically disadvantaged tracts identified in the boxplot.  \nIn summary, the findings strongly support the research question, demonstrating that low-income and minority neighborhoods in Philadelphia generally experience less equitable spatial access to nearby green spaces.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "assignment2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}