<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xinyuan(Christine) Cui">
<meta name="dcterms.date" content="2025-09-29">

<title>Assignment 1: Census Data Quality for Policy Decisions – Christine Cui - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Christine Cui - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/">
 <span class="dropdown-text">All Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-03-notes.html">
 <span class="dropdown-text">Week 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-04-notes.qmd">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab_0/">
 <span class="dropdown-text">Lab 0: dplyr Basics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_1/assignment1_template.html">
 <span class="dropdown-text">Assignment 1: Census Data Exploration</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xinyuan(Christine) Cui </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>Texas Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/assignments/assignment_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Assignments” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>assignments/assignment_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: assignments/assignment_1/your_file_name.qmd
      text: "Assignment 1: Census Data Exploration"</code></pre>
<p>If there is a special character like comma, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="st">"knitr"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(<span class="fu">installed.packages</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="st">"20068788c6e79d5716fbceb0dcd562ab23f74ca1"</span>, <span class="at">overwrite=</span><span class="cn">TRUE</span>, <span class="at">install =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "20068788c6e79d5716fbceb0dcd562ab23f74ca1"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>my_state <span class="ot">&lt;-</span> <span class="st">"TX"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>Texas</strong> for this analysis because: Texas is an ideal state for this analysis due to its unique combination of rapid population growth, demographic diversity, and significant geographic variation. These factors present specific data quality challenges that are critical to evaluating algorithmic fairness.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,        </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(               </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_household_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_population =</span> <span class="st">"B01003_001"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,            </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,                 </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,             </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span>              </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="ot">&lt;-</span> county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove state name（Texas）</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">NAME =</span> <span class="fu">str_remove</span>(NAME, <span class="st">", Texas"</span>),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove " County"</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">NAME =</span> <span class="fu">str_remove</span>(NAME, <span class="st">" County"</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(county_data_texas)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  GEOID NAME     median_household_inc…¹ median_household_inc…² total_populationE
  &lt;chr&gt; &lt;chr&gt;                     &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
1 48001 Anderson                  57445                   4562             58077
2 48003 Andrews                   86458                  16116             18362
3 48005 Angelina                  57055                   2484             86608
4 48007 Aransas                   58168                   6458             24048
5 48009 Archer                    69954                   8482              8649
6 48011 Armstro…                  70417                  14574              1912
# ℹ abbreviated names: ¹​median_household_incomeE, ²​median_household_incomeM
# ℹ 1 more variable: total_populationM &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="ot">&lt;-</span> county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MOE percentage</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_moe_pct =</span> (median_household_incomeM <span class="sc">/</span> median_household_incomeE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create reliability categories</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_reliability =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>      income_moe_pct <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High Confidence"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>      income_moe_pct <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> income_moe_pct <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Moderate Confidence"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      income_moe_pct <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Low Confidence"</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a flag for unreliable estimates</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">unreliable_income =</span> income_moe_pct <span class="sc">&gt;</span> <span class="dv">10</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(income_reliability) <span class="sc">%&gt;%</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  income_reliability      n percentage
  &lt;chr&gt;               &lt;int&gt;      &lt;dbl&gt;
1 High Confidence        58     22.8  
2 Low Confidence        113     44.5  
3 Moderate Confidence    82     32.3  
4 &lt;NA&gt;                    1      0.394</code></pre>
</div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(income_moe_pct)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">County Name</span><span class="st">`</span> <span class="ot">=</span> NAME,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Income</span><span class="st">`</span> <span class="ot">=</span> median_household_incomeE,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Margin of Error</span><span class="st">`</span> <span class="ot">=</span> median_household_incomeM,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE Percentage</span><span class="st">`</span> <span class="ot">=</span> income_moe_pct,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> income_reliability</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Top 5 Counties with The Highest MOE Percentages"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Counties with The Highest MOE Percentages</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">Margin of Error</th>
<th style="text-align: right;">MOE Percentage</th>
<th style="text-align: left;">Reliability Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jeff Davis</td>
<td style="text-align: right;">38125</td>
<td style="text-align: right;">25205</td>
<td style="text-align: right;">66.11</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Culberson</td>
<td style="text-align: right;">35924</td>
<td style="text-align: right;">18455</td>
<td style="text-align: right;">51.37</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">King</td>
<td style="text-align: right;">59375</td>
<td style="text-align: right;">29395</td>
<td style="text-align: right;">49.51</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kinney</td>
<td style="text-align: right;">52386</td>
<td style="text-align: right;">23728</td>
<td style="text-align: right;">45.29</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dimmit</td>
<td style="text-align: right;">27374</td>
<td style="text-align: right;">12374</td>
<td style="text-align: right;">45.20</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong> Based on these results, algorithmic funding decisions relying on the median income in counties like Jeff Davis and Culberson (with MOE&gt;50%) would be highly unreliable. These counties risk being poorly served because the true income value could be far outside the estimate, potentially leading to the algorithm severely over-allocating or under-allocating crucial resources. The extreme uncertainty is primarily due to small population size and low survey response rates, making precise income estimation statistically impossible in these sparsely populated areas.</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="ot">&lt;-</span> county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    income_moe_pct <span class="sc">&gt;</span> <span class="dv">30</span> <span class="sc">|</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    (income_moe_pct <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> income_moe_pct <span class="sc">&lt;=</span> <span class="dv">10</span>) <span class="sc">|</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    income_moe_pct <span class="sc">&lt;</span> <span class="dv">2</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select 3</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(income_reliability) <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="sc">%&gt;%</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">County Name</span><span class="st">`</span> <span class="ot">=</span> NAME,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Income</span><span class="st">`</span> <span class="ot">=</span> median_household_incomeE,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE Percentage</span><span class="st">`</span> <span class="ot">=</span> income_moe_pct,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> income_reliability</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"3 Counties Selected for Tract-Level Study"</span>,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits=</span> <span class="dv">2</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>3 Counties Selected for Tract-Level Study</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE Percentage</th>
<th style="text-align: left;">Reliability Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bexar</td>
<td style="text-align: right;">67275</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: left;">High Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brooks</td>
<td style="text-align: right;">30566</td>
<td style="text-align: right;">33.82</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anderson</td>
<td style="text-align: right;">57445</td>
<td style="text-align: right;">7.94</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Comment on the output:</strong> I deliberately selected counties representing the more extreme ends of the High and Low Confidence ranges. This strategy ensures a clearer and more impactful comparison of data quality. By focusing on these distinct cases (one very high confidence, one moderate, and one very low confidence), the tract-level analysis will better expose the full spectrum of data reliability issues that could affect the department’s funding algorithms.</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide</p>
<p><strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ethnicity_variables <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">white_alone =</span> <span class="st">"B03002_003"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Black_African_American =</span> <span class="st">"B03002_004"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Hispanic_Latino =</span> <span class="st">"B03002_012"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_population =</span> <span class="st">"B03002_001"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>selected_county_geoids <span class="ot">&lt;-</span> selected_counties<span class="sc">$</span>GEOID</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>selected_county_codes <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(selected_county_geoids, <span class="at">start =</span> <span class="sc">-</span><span class="dv">3</span>) <span class="co">#the last 3 numbers of GEOID is county codes</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>tract_data_texas <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,        </span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> ethnicity_variables,         </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,           </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> selected_county_codes, </span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,                 </span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,             </span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span>             </span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>tract_data_texas <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_white =</span> (white_aloneE <span class="sc">/</span> total_populationE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_black =</span> (Black_African_AmericanE <span class="sc">/</span> total_populationE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_hispanic =</span> (Hispanic_LatinoE <span class="sc">/</span> total_populationE) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>tract_data_texas <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>   <span class="at">Tract  =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"Census Tract </span><span class="sc">\\</span><span class="st">d+(?:</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+)?"</span>),</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>   <span class="at">County =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"[A-Za-z]+ County"</span>)</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tract_data_texas)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
  GEOID       NAME              white_aloneE white_aloneM Black_African_Americ…¹
  &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt;        &lt;dbl&gt;                  &lt;dbl&gt;
1 48001950100 Census Tract 950…         4061          682                    213
2 48001950401 Census Tract 950…         1073          308                   1569
3 48001950402 Census Tract 950…         1920          245                   2419
4 48001950500 Census Tract 950…         1924          381                    801
5 48001950600 Census Tract 950…         3287          674                    711
6 48001950700 Census Tract 950…          626          174                   1344
# ℹ abbreviated name: ¹​Black_African_AmericanE
# ℹ 10 more variables: Black_African_AmericanM &lt;dbl&gt;, Hispanic_LatinoE &lt;dbl&gt;,
#   Hispanic_LatinoM &lt;dbl&gt;, total_populationE &lt;dbl&gt;, total_populationM &lt;dbl&gt;,
#   pct_white &lt;dbl&gt;, pct_black &lt;dbl&gt;, pct_hispanic &lt;dbl&gt;, Tract &lt;chr&gt;,
#   County &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>top_hispanic_tract <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 按照 Hispanic/Latino 百分比 (pct_hispanic) 降序排列</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_hispanic)) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>top_hispanic_tract <span class="sc">%&gt;%</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Tract with the Highest Percentage of Hispanic/Latino Residents"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tract with the Highest Percentage of Hispanic/Latino Residents</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">GEOID</th>
<th style="text-align: left;">NAME</th>
<th style="text-align: right;">white_aloneE</th>
<th style="text-align: right;">white_aloneM</th>
<th style="text-align: right;">Black_African_AmericanE</th>
<th style="text-align: right;">Black_African_AmericanM</th>
<th style="text-align: right;">Hispanic_LatinoE</th>
<th style="text-align: right;">Hispanic_LatinoM</th>
<th style="text-align: right;">total_populationE</th>
<th style="text-align: right;">total_populationM</th>
<th style="text-align: right;">pct_white</th>
<th style="text-align: right;">pct_black</th>
<th style="text-align: right;">pct_hispanic</th>
<th style="text-align: left;">Tract</th>
<th style="text-align: left;">County</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">48029160100</td>
<td style="text-align: left;">Census Tract 1601; Bexar County; Texas</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">6931</td>
<td style="text-align: right;">1114</td>
<td style="text-align: right;">6949</td>
<td style="text-align: right;">1112</td>
<td style="text-align: right;">0.2590301</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">99.74097</td>
<td style="text-align: left;">Census Tract 1601</td>
<td style="text-align: left;">Bexar County</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>county_demographics_summary <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. 按照县进行分组</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(County) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. 计算每个县的汇总统计量</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_white =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_population_E =</span> <span class="fu">sum</span>(total_populationE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  county_demographics_summary <span class="sc">%&gt;%</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">County</span><span class="st">`</span> <span class="ot">=</span> County,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Tracts</span><span class="st">`</span> <span class="ot">=</span> number_of_tracts,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Avg White/%</span><span class="st">`</span> <span class="ot">=</span> avg_pct_white,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Avg Black/%</span><span class="st">`</span> <span class="ot">=</span> avg_pct_black,</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Avg Hispanic/%</span><span class="st">`</span> <span class="ot">=</span> avg_pct_hispanic,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Total Pop</span><span class="st">`</span> <span class="ot">=</span> total_population_E</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Average Demographics by County"</span>,</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Demographics by County</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Tracts</th>
<th style="text-align: right;">Avg White/%</th>
<th style="text-align: right;">Avg Black/%</th>
<th style="text-align: right;">Avg Hispanic/%</th>
<th style="text-align: right;">Total Pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anderson County</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">56.89</td>
<td style="text-align: right;">18.80</td>
<td style="text-align: right;">17.98</td>
<td style="text-align: right;">58077</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bexar County</td>
<td style="text-align: right;">375</td>
<td style="text-align: right;">25.50</td>
<td style="text-align: right;">6.42</td>
<td style="text-align: right;">62.54</td>
<td style="text-align: right;">2014059</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brooks County</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">89.16</td>
<td style="text-align: right;">7059</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>tract_data_texas <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MOE percentage</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">white_moe_pct =</span> (white_aloneM <span class="sc">/</span> white_aloneE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">black_moe_pct =</span> (Black_African_AmericanM <span class="sc">/</span> Black_African_AmericanE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">hispanic_moe_pct =</span> (Hispanic_LatinoM <span class="sc">/</span> Hispanic_LatinoE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">demographic_reliability =</span> <span class="fu">ifelse</span>(</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>      white_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> black_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> hispanic_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span>,<span class="st">"High MOE"</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Acceptable"</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(demographic_reliability) <span class="sc">%&gt;%</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  demographic_reliability     n percentage
  &lt;chr&gt;                   &lt;int&gt;      &lt;dbl&gt;
1 High MOE                  389        100</code></pre>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>tract_reliability_comparison <span class="ot">&lt;-</span> tract_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(demographic_reliability) <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Number_of_Tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Population =</span> <span class="fu">mean</span>(total_populationE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Pct_White =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Pct_Black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Pct_Hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>tract_reliability_comparison <span class="sc">%&gt;%</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Group</span><span class="st">`</span> <span class="ot">=</span> demographic_reliability,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Tract Count</span><span class="st">`</span> <span class="ot">=</span> Number_of_Tracts,</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Avg Pop. Size</span><span class="st">`</span> <span class="ot">=</span> Avg_Population, </span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Avg White/%</span><span class="st">`</span> <span class="ot">=</span> Avg_Pct_White,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Avg Black/%</span><span class="st">`</span> <span class="ot">=</span> Avg_Pct_Black,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Avg Hispanic/%</span><span class="st">`</span> <span class="ot">=</span> Avg_Pct_Hispanic</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span>             <span class="co"># KEY：使用管道符将数据框传递给 kable</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Comparison of Tract Characteristics by Data Reliability"</span>,</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Tract Characteristics by Data Reliability</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Reliability Group</th>
<th style="text-align: right;">Tract Count</th>
<th style="text-align: right;">Avg Pop. Size</th>
<th style="text-align: right;">Avg White/%</th>
<th style="text-align: right;">Avg Black/%</th>
<th style="text-align: right;">Avg Hispanic/%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High MOE</td>
<td style="text-align: right;">389</td>
<td style="text-align: right;">5344.97</td>
<td style="text-align: right;">26.39</td>
<td style="text-align: right;">6.78</td>
<td style="text-align: right;">61.29</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Pattern Analysis:</strong></p>
<p>The analysis reveals an extreme, systemic data quality issue: 100% of the tracts in the selected focus areas fall into the High MOE category. This means data reliability is not merely poor in isolated cases, but universally insufficient across these tracts. The average population size for all these unreliable tracts is around 5,345 people, with a high average concentration of Hispanic residents (61.29%). This pattern strongly suggests that in small, high-minority counties, the reliability of demographic estimates completely breaks down at the tract level. The lack of sufficient sample size in these relatively small, rural, tracts makes the ACS data inherently unstable. Consequently, any algorithm relying on this demographic data in these counties would be making resource allocation decisions based on pure statistical uncertainty, disproportionately impacting Hispanic-majority communities with unreliable information.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong> 1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses? 2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings? 3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk? 4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong></p>
<p>The analysis reveals a two-type, systematic breakdown in data reliability: At the county level, high MOE is concentrated in sparsely populated counties like Jeff Davis and Culberson. These areas immediately fail basic reliability thresholds for household income estimates. At the county level, 100% of all tracts examined fell into the High Uncertainty category, showing an MOE greater than 15% on demographic variables. This means data quality completely collapses at the neighborhood level within these regions, making reliable demographic information universally insufficient for use in funding or allocation decisions.</p>
<p>Communities with the highest risk of algorithmic bias are those that are small, rural, and possess a high concentration of minority residents. The tracts flagged as universally unreliable show an average of 61.29% Hispanic residents. Algorithms relying on this fundamentally flawed data risk systematically under-serving these communities, as any resource allocation based on the estimate would carry a high degree of statistical uncertainty, effectively rendering the data unusable for precise needs assessment.</p>
<p>The underlying factor driving both data quality issues and the resulting bias risk is the insufficient statistical sample size combined with geographical isolation. In sparsely populated, often rural counties, the ACS cannot collect enough household responses to produce stable estimates for either income or demographics. Because high-minority communities are overrepresented in these low-population areas in Texas, the data gaps systematically align with ethnic lines, translating a statistical problem into an undeniable equity problem.</p>
<p>To reduce this systemic risk and ensure equitable allocation, the Department should implement the following strategic measures: 1. Implement a strict rule requiring that any data used by the allocation algorithm must have an MOE percentage below a pre-defined threshold (e.g., 10%). Funding allocation logic must be halted if this threshold is breached. 2. For all counties or tracts flagged as “High Uncertainty” (MOE&gt;15%), the algorithm must default to using supplementary, non-ACS data rather than relying on unreliable census estimates. 3. Program the algorithm to automatically flag and defer funding decisions for any tract with high data uncertainty to a human review committee, ensuring local context and qualitative data are applied where quantitative data is weakest.</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>county_data_texas <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">County Name</span><span class="st">`</span> <span class="ot">=</span> NAME,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Income</span><span class="st">`</span> <span class="ot">=</span> median_household_incomeE,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE Percentage</span><span class="st">`</span> <span class="ot">=</span> income_moe_pct,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> income_reliability</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Algorithm Recommendation</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>      <span class="co"># High Confidence: MOE &lt; 5%</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"High Confidence"</span> <span class="sc">~</span> <span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Moderate Confidence: MOE 5-10%</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Moderate Confidence"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Low Confidence: MOE &gt; 10%</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Algorithmic Implementation Framework"</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span> <span class="co"># 保留两位小数</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Algorithmic Implementation Framework</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE Percentage</th>
<th style="text-align: left;">Reliability Category</th>
<th style="text-align: left;">Algorithm Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anderson</td>
<td style="text-align: right;">57445</td>
<td style="text-align: right;">7.94</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Andrews</td>
<td style="text-align: right;">86458</td>
<td style="text-align: right;">18.64</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Angelina</td>
<td style="text-align: right;">57055</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aransas</td>
<td style="text-align: right;">58168</td>
<td style="text-align: right;">11.10</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Archer</td>
<td style="text-align: right;">69954</td>
<td style="text-align: right;">12.13</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Armstrong</td>
<td style="text-align: right;">70417</td>
<td style="text-align: right;">20.70</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Atascosa</td>
<td style="text-align: right;">67442</td>
<td style="text-align: right;">6.39</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austin</td>
<td style="text-align: right;">73556</td>
<td style="text-align: right;">6.47</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bailey</td>
<td style="text-align: right;">69830</td>
<td style="text-align: right;">18.79</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bandera</td>
<td style="text-align: right;">70965</td>
<td style="text-align: right;">8.05</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bastrop</td>
<td style="text-align: right;">80151</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baylor</td>
<td style="text-align: right;">52716</td>
<td style="text-align: right;">25.14</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bee</td>
<td style="text-align: right;">50283</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bell</td>
<td style="text-align: right;">62858</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bexar</td>
<td style="text-align: right;">67275</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Blanco</td>
<td style="text-align: right;">79717</td>
<td style="text-align: right;">9.35</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Borden</td>
<td style="text-align: right;">80625</td>
<td style="text-align: right;">24.88</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bosque</td>
<td style="text-align: right;">63868</td>
<td style="text-align: right;">6.05</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bowie</td>
<td style="text-align: right;">56628</td>
<td style="text-align: right;">4.12</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazoria</td>
<td style="text-align: right;">91972</td>
<td style="text-align: right;">3.31</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brazos</td>
<td style="text-align: right;">57562</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brewster</td>
<td style="text-align: right;">47747</td>
<td style="text-align: right;">10.97</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Briscoe</td>
<td style="text-align: right;">35446</td>
<td style="text-align: right;">27.64</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brooks</td>
<td style="text-align: right;">30566</td>
<td style="text-align: right;">33.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brown</td>
<td style="text-align: right;">53792</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Burleson</td>
<td style="text-align: right;">71745</td>
<td style="text-align: right;">6.53</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burnet</td>
<td style="text-align: right;">71482</td>
<td style="text-align: right;">8.09</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Caldwell</td>
<td style="text-align: right;">66779</td>
<td style="text-align: right;">6.96</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calhoun</td>
<td style="text-align: right;">62267</td>
<td style="text-align: right;">9.92</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Callahan</td>
<td style="text-align: right;">63906</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cameron</td>
<td style="text-align: right;">47435</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Camp</td>
<td style="text-align: right;">53968</td>
<td style="text-align: right;">7.64</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carson</td>
<td style="text-align: right;">83199</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cass</td>
<td style="text-align: right;">54303</td>
<td style="text-align: right;">6.82</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Castro</td>
<td style="text-align: right;">59886</td>
<td style="text-align: right;">17.03</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chambers</td>
<td style="text-align: right;">106103</td>
<td style="text-align: right;">8.28</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cherokee</td>
<td style="text-align: right;">56971</td>
<td style="text-align: right;">8.45</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Childress</td>
<td style="text-align: right;">56063</td>
<td style="text-align: right;">29.34</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clay</td>
<td style="text-align: right;">75227</td>
<td style="text-align: right;">7.11</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cochran</td>
<td style="text-align: right;">41597</td>
<td style="text-align: right;">16.97</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coke</td>
<td style="text-align: right;">40230</td>
<td style="text-align: right;">13.80</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coleman</td>
<td style="text-align: right;">51034</td>
<td style="text-align: right;">7.95</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Collin</td>
<td style="text-align: right;">113255</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Collingsworth</td>
<td style="text-align: right;">52045</td>
<td style="text-align: right;">22.02</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colorado</td>
<td style="text-align: right;">63352</td>
<td style="text-align: right;">8.17</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Comal</td>
<td style="text-align: right;">93744</td>
<td style="text-align: right;">2.83</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comanche</td>
<td style="text-align: right;">57383</td>
<td style="text-align: right;">13.32</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Concho</td>
<td style="text-align: right;">55750</td>
<td style="text-align: right;">27.87</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cooke</td>
<td style="text-align: right;">66374</td>
<td style="text-align: right;">8.36</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coryell</td>
<td style="text-align: right;">63281</td>
<td style="text-align: right;">3.62</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cottle</td>
<td style="text-align: right;">47625</td>
<td style="text-align: right;">37.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crane</td>
<td style="text-align: right;">71364</td>
<td style="text-align: right;">32.89</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crockett</td>
<td style="text-align: right;">64103</td>
<td style="text-align: right;">33.95</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crosby</td>
<td style="text-align: right;">50268</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Culberson</td>
<td style="text-align: right;">35924</td>
<td style="text-align: right;">51.37</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dallam</td>
<td style="text-align: right;">71969</td>
<td style="text-align: right;">9.75</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dallas</td>
<td style="text-align: right;">70732</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dawson</td>
<td style="text-align: right;">45268</td>
<td style="text-align: right;">27.64</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deaf Smith</td>
<td style="text-align: right;">51942</td>
<td style="text-align: right;">6.01</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Delta</td>
<td style="text-align: right;">68491</td>
<td style="text-align: right;">27.75</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denton</td>
<td style="text-align: right;">104180</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">DeWitt</td>
<td style="text-align: right;">61100</td>
<td style="text-align: right;">7.86</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dickens</td>
<td style="text-align: right;">46638</td>
<td style="text-align: right;">13.62</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dimmit</td>
<td style="text-align: right;">27374</td>
<td style="text-align: right;">45.20</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Donley</td>
<td style="text-align: right;">51711</td>
<td style="text-align: right;">12.45</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duval</td>
<td style="text-align: right;">50697</td>
<td style="text-align: right;">20.28</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eastland</td>
<td style="text-align: right;">52902</td>
<td style="text-align: right;">12.21</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ector</td>
<td style="text-align: right;">70566</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Edwards</td>
<td style="text-align: right;">40809</td>
<td style="text-align: right;">27.09</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ellis</td>
<td style="text-align: right;">93248</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Paso</td>
<td style="text-align: right;">55417</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Erath</td>
<td style="text-align: right;">59654</td>
<td style="text-align: right;">6.73</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Falls</td>
<td style="text-align: right;">45172</td>
<td style="text-align: right;">15.35</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fannin</td>
<td style="text-align: right;">65835</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fayette</td>
<td style="text-align: right;">72881</td>
<td style="text-align: right;">5.03</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fisher</td>
<td style="text-align: right;">60461</td>
<td style="text-align: right;">8.19</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Floyd</td>
<td style="text-align: right;">49321</td>
<td style="text-align: right;">8.99</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Foard</td>
<td style="text-align: right;">41944</td>
<td style="text-align: right;">20.94</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fort Bend</td>
<td style="text-align: right;">109987</td>
<td style="text-align: right;">2.64</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Franklin</td>
<td style="text-align: right;">67915</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Freestone</td>
<td style="text-align: right;">55902</td>
<td style="text-align: right;">10.53</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frio</td>
<td style="text-align: right;">56042</td>
<td style="text-align: right;">30.34</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gaines</td>
<td style="text-align: right;">73299</td>
<td style="text-align: right;">13.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Galveston</td>
<td style="text-align: right;">83913</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Garza</td>
<td style="text-align: right;">56215</td>
<td style="text-align: right;">34.96</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gillespie</td>
<td style="text-align: right;">70162</td>
<td style="text-align: right;">8.15</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glasscock</td>
<td style="text-align: right;">112188</td>
<td style="text-align: right;">27.86</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Goliad</td>
<td style="text-align: right;">58125</td>
<td style="text-align: right;">25.84</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gonzales</td>
<td style="text-align: right;">64255</td>
<td style="text-align: right;">8.43</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gray</td>
<td style="text-align: right;">54563</td>
<td style="text-align: right;">7.16</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grayson</td>
<td style="text-align: right;">66608</td>
<td style="text-align: right;">3.60</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gregg</td>
<td style="text-align: right;">63811</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grimes</td>
<td style="text-align: right;">63484</td>
<td style="text-align: right;">9.10</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guadalupe</td>
<td style="text-align: right;">88111</td>
<td style="text-align: right;">3.93</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hale</td>
<td style="text-align: right;">50721</td>
<td style="text-align: right;">8.97</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hall</td>
<td style="text-align: right;">43873</td>
<td style="text-align: right;">10.96</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hamilton</td>
<td style="text-align: right;">54890</td>
<td style="text-align: right;">17.27</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hansford</td>
<td style="text-align: right;">62350</td>
<td style="text-align: right;">19.70</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hardeman</td>
<td style="text-align: right;">60455</td>
<td style="text-align: right;">15.33</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hardin</td>
<td style="text-align: right;">70164</td>
<td style="text-align: right;">5.15</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harris</td>
<td style="text-align: right;">70789</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Harrison</td>
<td style="text-align: right;">63427</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hartley</td>
<td style="text-align: right;">78065</td>
<td style="text-align: right;">27.00</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Haskell</td>
<td style="text-align: right;">52786</td>
<td style="text-align: right;">16.33</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hays</td>
<td style="text-align: right;">79990</td>
<td style="text-align: right;">3.73</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hemphill</td>
<td style="text-align: right;">67798</td>
<td style="text-align: right;">27.70</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Henderson</td>
<td style="text-align: right;">59778</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hidalgo</td>
<td style="text-align: right;">49371</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hill</td>
<td style="text-align: right;">60669</td>
<td style="text-align: right;">6.01</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hockley</td>
<td style="text-align: right;">53283</td>
<td style="text-align: right;">7.51</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hood</td>
<td style="text-align: right;">80013</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hopkins</td>
<td style="text-align: right;">63766</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Houston</td>
<td style="text-align: right;">51043</td>
<td style="text-align: right;">10.50</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Howard</td>
<td style="text-align: right;">67243</td>
<td style="text-align: right;">6.53</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hudspeth</td>
<td style="text-align: right;">35163</td>
<td style="text-align: right;">23.20</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hunt</td>
<td style="text-align: right;">66885</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hutchinson</td>
<td style="text-align: right;">62211</td>
<td style="text-align: right;">7.55</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Irion</td>
<td style="text-align: right;">54708</td>
<td style="text-align: right;">16.96</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jack</td>
<td style="text-align: right;">58861</td>
<td style="text-align: right;">13.22</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jackson</td>
<td style="text-align: right;">67176</td>
<td style="text-align: right;">17.91</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jasper</td>
<td style="text-align: right;">48818</td>
<td style="text-align: right;">9.84</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jeff Davis</td>
<td style="text-align: right;">38125</td>
<td style="text-align: right;">66.11</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jefferson</td>
<td style="text-align: right;">57294</td>
<td style="text-align: right;">2.91</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jim Hogg</td>
<td style="text-align: right;">42292</td>
<td style="text-align: right;">13.64</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jim Wells</td>
<td style="text-align: right;">46626</td>
<td style="text-align: right;">12.69</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Johnson</td>
<td style="text-align: right;">77058</td>
<td style="text-align: right;">3.06</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jones</td>
<td style="text-align: right;">59361</td>
<td style="text-align: right;">10.04</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Karnes</td>
<td style="text-align: right;">57798</td>
<td style="text-align: right;">14.47</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kaufman</td>
<td style="text-align: right;">84075</td>
<td style="text-align: right;">4.11</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kendall</td>
<td style="text-align: right;">104196</td>
<td style="text-align: right;">8.26</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kenedy</td>
<td style="text-align: right;">45455</td>
<td style="text-align: right;">25.12</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kent</td>
<td style="text-align: right;">68553</td>
<td style="text-align: right;">15.57</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kerr</td>
<td style="text-align: right;">66713</td>
<td style="text-align: right;">6.23</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kimble</td>
<td style="text-align: right;">62386</td>
<td style="text-align: right;">22.58</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">King</td>
<td style="text-align: right;">59375</td>
<td style="text-align: right;">49.51</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kinney</td>
<td style="text-align: right;">52386</td>
<td style="text-align: right;">45.29</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kleberg</td>
<td style="text-align: right;">52487</td>
<td style="text-align: right;">9.50</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Knox</td>
<td style="text-align: right;">48750</td>
<td style="text-align: right;">9.82</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lamar</td>
<td style="text-align: right;">58246</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lamb</td>
<td style="text-align: right;">54519</td>
<td style="text-align: right;">8.61</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lampasas</td>
<td style="text-align: right;">73269</td>
<td style="text-align: right;">7.44</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">La Salle</td>
<td style="text-align: right;">62798</td>
<td style="text-align: right;">26.04</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lavaca</td>
<td style="text-align: right;">58530</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lee</td>
<td style="text-align: right;">66448</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leon</td>
<td style="text-align: right;">57363</td>
<td style="text-align: right;">12.04</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liberty</td>
<td style="text-align: right;">59605</td>
<td style="text-align: right;">6.69</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limestone</td>
<td style="text-align: right;">53102</td>
<td style="text-align: right;">7.12</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lipscomb</td>
<td style="text-align: right;">71625</td>
<td style="text-align: right;">12.92</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Live Oak</td>
<td style="text-align: right;">55949</td>
<td style="text-align: right;">17.98</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Llano</td>
<td style="text-align: right;">64241</td>
<td style="text-align: right;">8.81</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Loving</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lubbock</td>
<td style="text-align: right;">61911</td>
<td style="text-align: right;">3.54</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lynn</td>
<td style="text-align: right;">52996</td>
<td style="text-align: right;">7.09</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">McCulloch</td>
<td style="text-align: right;">53214</td>
<td style="text-align: right;">16.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">McLennan</td>
<td style="text-align: right;">59781</td>
<td style="text-align: right;">3.19</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">McMullen</td>
<td style="text-align: right;">60313</td>
<td style="text-align: right;">41.18</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madison</td>
<td style="text-align: right;">65768</td>
<td style="text-align: right;">9.56</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marion</td>
<td style="text-align: right;">48040</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Martin</td>
<td style="text-align: right;">70217</td>
<td style="text-align: right;">27.10</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mason</td>
<td style="text-align: right;">77583</td>
<td style="text-align: right;">15.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matagorda</td>
<td style="text-align: right;">56412</td>
<td style="text-align: right;">6.28</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maverick</td>
<td style="text-align: right;">48497</td>
<td style="text-align: right;">10.10</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medina</td>
<td style="text-align: right;">73060</td>
<td style="text-align: right;">4.04</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Menard</td>
<td style="text-align: right;">40945</td>
<td style="text-align: right;">17.91</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Midland</td>
<td style="text-align: right;">90123</td>
<td style="text-align: right;">5.80</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Milam</td>
<td style="text-align: right;">56985</td>
<td style="text-align: right;">5.92</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mills</td>
<td style="text-align: right;">59315</td>
<td style="text-align: right;">9.26</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mitchell</td>
<td style="text-align: right;">49869</td>
<td style="text-align: right;">12.52</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montague</td>
<td style="text-align: right;">63336</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montgomery</td>
<td style="text-align: right;">95946</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moore</td>
<td style="text-align: right;">59041</td>
<td style="text-align: right;">6.55</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Morris</td>
<td style="text-align: right;">51532</td>
<td style="text-align: right;">6.71</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Motley</td>
<td style="text-align: right;">66528</td>
<td style="text-align: right;">8.43</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nacogdoches</td>
<td style="text-align: right;">51153</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Navarro</td>
<td style="text-align: right;">56261</td>
<td style="text-align: right;">7.70</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Newton</td>
<td style="text-align: right;">38871</td>
<td style="text-align: right;">16.91</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nolan</td>
<td style="text-align: right;">47437</td>
<td style="text-align: right;">7.72</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nueces</td>
<td style="text-align: right;">64027</td>
<td style="text-align: right;">2.26</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ochiltree</td>
<td style="text-align: right;">62240</td>
<td style="text-align: right;">17.77</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oldham</td>
<td style="text-align: right;">71103</td>
<td style="text-align: right;">11.17</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">71910</td>
<td style="text-align: right;">7.89</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Palo Pinto</td>
<td style="text-align: right;">65242</td>
<td style="text-align: right;">4.40</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Panola</td>
<td style="text-align: right;">58205</td>
<td style="text-align: right;">18.34</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parker</td>
<td style="text-align: right;">95721</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parmer</td>
<td style="text-align: right;">65575</td>
<td style="text-align: right;">13.74</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pecos</td>
<td style="text-align: right;">59325</td>
<td style="text-align: right;">17.15</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polk</td>
<td style="text-align: right;">57315</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Potter</td>
<td style="text-align: right;">47974</td>
<td style="text-align: right;">3.95</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Presidio</td>
<td style="text-align: right;">29012</td>
<td style="text-align: right;">23.98</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rains</td>
<td style="text-align: right;">60291</td>
<td style="text-align: right;">10.78</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Randall</td>
<td style="text-align: right;">78038</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reagan</td>
<td style="text-align: right;">70319</td>
<td style="text-align: right;">12.82</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Real</td>
<td style="text-align: right;">46842</td>
<td style="text-align: right;">32.96</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Red River</td>
<td style="text-align: right;">44583</td>
<td style="text-align: right;">9.73</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reeves</td>
<td style="text-align: right;">57487</td>
<td style="text-align: right;">22.06</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Refugio</td>
<td style="text-align: right;">54304</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Roberts</td>
<td style="text-align: right;">62667</td>
<td style="text-align: right;">14.22</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robertson</td>
<td style="text-align: right;">59410</td>
<td style="text-align: right;">17.70</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rockwall</td>
<td style="text-align: right;">121303</td>
<td style="text-align: right;">3.78</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Runnels</td>
<td style="text-align: right;">55424</td>
<td style="text-align: right;">5.97</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rusk</td>
<td style="text-align: right;">61661</td>
<td style="text-align: right;">9.85</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sabine</td>
<td style="text-align: right;">47061</td>
<td style="text-align: right;">16.90</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Augustine</td>
<td style="text-align: right;">45888</td>
<td style="text-align: right;">9.69</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Jacinto</td>
<td style="text-align: right;">54839</td>
<td style="text-align: right;">12.97</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Patricio</td>
<td style="text-align: right;">63842</td>
<td style="text-align: right;">6.88</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Saba</td>
<td style="text-align: right;">54087</td>
<td style="text-align: right;">16.38</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schleicher</td>
<td style="text-align: right;">53774</td>
<td style="text-align: right;">15.15</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scurry</td>
<td style="text-align: right;">58932</td>
<td style="text-align: right;">21.39</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shackelford</td>
<td style="text-align: right;">60924</td>
<td style="text-align: right;">14.04</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shelby</td>
<td style="text-align: right;">49231</td>
<td style="text-align: right;">9.96</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sherman</td>
<td style="text-align: right;">66169</td>
<td style="text-align: right;">27.93</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Smith</td>
<td style="text-align: right;">69053</td>
<td style="text-align: right;">3.19</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Somervell</td>
<td style="text-align: right;">87899</td>
<td style="text-align: right;">33.73</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Starr</td>
<td style="text-align: right;">35979</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stephens</td>
<td style="text-align: right;">44712</td>
<td style="text-align: right;">18.85</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sterling</td>
<td style="text-align: right;">63558</td>
<td style="text-align: right;">22.25</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stonewall</td>
<td style="text-align: right;">66591</td>
<td style="text-align: right;">32.48</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sutton</td>
<td style="text-align: right;">56778</td>
<td style="text-align: right;">22.74</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Swisher</td>
<td style="text-align: right;">40290</td>
<td style="text-align: right;">13.69</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tarrant</td>
<td style="text-align: right;">78872</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taylor</td>
<td style="text-align: right;">61806</td>
<td style="text-align: right;">3.90</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Terrell</td>
<td style="text-align: right;">52813</td>
<td style="text-align: right;">21.03</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Terry</td>
<td style="text-align: right;">42694</td>
<td style="text-align: right;">10.93</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Throckmorton</td>
<td style="text-align: right;">55221</td>
<td style="text-align: right;">21.09</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Titus</td>
<td style="text-align: right;">57634</td>
<td style="text-align: right;">8.12</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tom Green</td>
<td style="text-align: right;">67215</td>
<td style="text-align: right;">4.68</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Travis</td>
<td style="text-align: right;">92731</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trinity</td>
<td style="text-align: right;">51165</td>
<td style="text-align: right;">11.37</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tyler</td>
<td style="text-align: right;">50898</td>
<td style="text-align: right;">10.34</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Upshur</td>
<td style="text-align: right;">60456</td>
<td style="text-align: right;">7.74</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Upton</td>
<td style="text-align: right;">55284</td>
<td style="text-align: right;">21.72</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uvalde</td>
<td style="text-align: right;">55000</td>
<td style="text-align: right;">15.28</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Val Verde</td>
<td style="text-align: right;">57250</td>
<td style="text-align: right;">8.01</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Van Zandt</td>
<td style="text-align: right;">62334</td>
<td style="text-align: right;">8.10</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Victoria</td>
<td style="text-align: right;">66308</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Walker</td>
<td style="text-align: right;">47193</td>
<td style="text-align: right;">6.32</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Waller</td>
<td style="text-align: right;">71643</td>
<td style="text-align: right;">5.98</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ward</td>
<td style="text-align: right;">70771</td>
<td style="text-align: right;">12.60</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">70043</td>
<td style="text-align: right;">9.41</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Webb</td>
<td style="text-align: right;">59984</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wharton</td>
<td style="text-align: right;">59712</td>
<td style="text-align: right;">6.84</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wheeler</td>
<td style="text-align: right;">58158</td>
<td style="text-align: right;">14.24</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wichita</td>
<td style="text-align: right;">58862</td>
<td style="text-align: right;">3.24</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wilbarger</td>
<td style="text-align: right;">50769</td>
<td style="text-align: right;">18.36</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Willacy</td>
<td style="text-align: right;">42839</td>
<td style="text-align: right;">13.05</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Williamson</td>
<td style="text-align: right;">102851</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wilson</td>
<td style="text-align: right;">89708</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Winkler</td>
<td style="text-align: right;">89155</td>
<td style="text-align: right;">16.06</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wise</td>
<td style="text-align: right;">85385</td>
<td style="text-align: right;">6.07</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wood</td>
<td style="text-align: right;">61748</td>
<td style="text-align: right;">6.02</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yoakum</td>
<td style="text-align: right;">80317</td>
<td style="text-align: right;">8.81</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Young</td>
<td style="text-align: right;">65565</td>
<td style="text-align: right;">16.86</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zapata</td>
<td style="text-align: right;">35061</td>
<td style="text-align: right;">10.72</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zavala</td>
<td style="text-align: right;">49243</td>
<td style="text-align: right;">28.78</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><strong>Counties suitable for immediate algorithmic implementation:</strong></li>
</ol>
<p>Counties categorized as High Confidence (those with median income MOE below 5%) are suitable. These typically include large, urban counties with stable estimates, such as Harris or Dallas County. They are appropriate because their data is statistically stable, meaning resource allocations based on the income estimates are highly reliable (&gt;95% certainty), minimizing the risk of systemic misallocation.</p>
<ol start="2" type="1">
<li><strong>Counties requiring additional oversight:</strong></li>
</ol>
<p>Counties categorized as Moderate Confidence (median income MOE between 5% and 10%) should be deployed with caution. The Department must implement real-time monitoring to compare algorithmic allocation decisions against actual service uptake and ground-level case worker reports. A 5%-10% uncertainty range requires human oversight to validate outcomes and trigger manual review if the allocation pattern appears to deviate significantly from expected need.</p>
<ol start="3" type="1">
<li><strong>Counties needing alternative approaches:</strong></li>
</ol>
<p>All Low Confidence counties (MOE&gt;10%), especially those with extreme uncertainty like Jeff Davis (MOE≈66%) and Culberson (MOE≈53%), must have standard algorithmic application immediately suspended. For these areas, where tract-level data is universally unreliable and serves high Hispanic populations, the Department must transition to manual case worker review for needs assessment, or invest in small, targeted administrative surveys as a more reliable proxy for need than the ACS income estimates.</p>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<ol type="1">
<li><p>How do the tracts flagged with High MOE cluster geographically, and is there a measurable correlation between these clusters and existing disparities in access to Department resources or social infrastructure?</p></li>
<li><p>Beyond the Hispanic population, are High MOE issues equally prevalent across other small, concentrated minority groups (e.g., specific Native American or Asian subgroups), or is the sample size challenge uniquely impacting the Hispanic population in the Texas border regions?</p></li>
</ol>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on September 19, 2025</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version 4.5.1 - Census API key required for replication - Complete code and documentation available at: https://github.com/MUSA-5080-Fall-2025/portfolio-setup-ChristineCui12</p>
<p><strong>Methodology Notes:</strong></p>
<p>The analysis employed several deliberate choices to focus the data quality evaluation. First, all estimates were sourced from the American Community Survey (ACS) 2018-2022 5-Year Estimates to ensure the most geographically detailed and statistically stable data available for tract-level analysis. Second, the three focus counties were intentionally selected based on the MOE analysis to represent the extremes of data reliability (High, Moderate, Low Confidence MOE ranges) rather than simply picking counties near the confidence boundaries. This was done to maximize the observed contrast in data quality patterns during the tract-level deep dive. Third, a conservative 15% MOE threshold was set for the tract-level demographic variables. If the MOE for any of the three major demographic groups (White, Black, Hispanic) exceeded this threshold, the entire tract was flagged as High MOE.</p>
<p><strong>Limitations:</strong></p>
<p>The findings are restricted to Texas and the three specifically selected counties. The conclusion that 100% of tracts in the focus area are unreliable is an extreme finding that may not be generalizable to counties in other parts of the state or country. Besides, the use of 5-Year ACS estimates means the data represents a rolling average from 2018 to 2022. This dampens volatility but may mask rapid economic changes or population shifts that have occurred since the beginning of the period.</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul>
<li>[√] All code chunks run without errors</li>
<li>[√] All “[Fill this in]” prompts have been completed</li>
<li>[√] Tables are properly formatted and readable</li>
<li>[√] Executive summary addresses all four required components</li>
<li>[√] Portfolio navigation includes this assignment</li>
<li>[√] Census API key is properly set</li>
<li>[√] Document renders correctly to HTML</li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/assignments/assignment_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>